title: "Ritch Builders Company"
author: "Ritchie Navarro"
description: "Independent Contractor based in San Diego County"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Projects", file: "projects.md"}
  - {title: "Portfolio", file: "portfolio.md"}
  - {title: "About", file: "index.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail", icon: envelope, url: "mailto:ritchbuilders.com"}
  - {title: "Facebook", icon: facebook, url: "https://www.facebook.com/Ritchbuilders"}
  - {title: "Need more info?", icon: star, url: "https://www.contractorconnection.com/6-reasons-to-choose-a-professional-home-improvement-contractor-2/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
