title: "Roula Nassif"
author: "Roula Nassif"
description: "Université Côte d'Azur"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "about.md", title: "About me"}
  - {file: "projects.md", title: "Research projects and positions"}
  - {file: "README.md", title: "Publications"}
  # - {file: "README.md", title: "Teaching"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "roula.nassif@univ-cotedazur.fr"}
#  - {title: Github, icon: github, url: "https://github.com/Roulanassif"}
#  - {title: Subscribe, icon: rss, url: "https://twitter.com/NassifRoula"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
