title: "René Kooiker"
author: "René J. Kooiker"
description: "Made with Jekyll"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Blog", icon: home} # this is the front page
  - {file: "aboutme.md", title: "About Me", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rkooiker18@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/rjkooiker"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/rene-kooiker/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-titles-from-headings
